### ISSUE TITLE
0.2.3: missing git tag

### ISSUE THREAD

**Issue by kloczek** [jbwdevries/pytest-integration#12]
According tohttps://pypi.org/project/pytest-integration/ latest version is 0.2.3 however here git tag is missing.
Is it possible to add missing git tag? 🤔

**Comment by jbwdevries** [comment]
Done, thanks for pointing this out :+1:

**Comment by kloczek** [comment]
Thank you 👍 😄

**Comment by kloczek** [comment]
If may I ask next time to make releae as well to appear on https://github.com/jbwdevries/pytest-integration/releases).
Issue is that github automatically sends notyfications of releases (and not new tags).
One more time .. thank you 👍

**Comment by jbwdevries** [comment]
I didn't know (more used to Gitlab), I 'll try to do that next time :+1:
